import { Router, type IRouter } from "express";
import healthRouter from "./health";
import supplementsRouter from "./supplements";
import activitiesRouter from "./activities";
import logsRouter from "./logs";
import insightsRouter from "./insights";
import openaiRouter from "./openai";
import natalRouter from "./natal";
import checkInsRouter from "./checkIns";
import bodyWeatherRouter from "./bodyWeather";
import astroDebugRouter from "./astroDebug";
import locationSearchRouter from "./locationSearch";
import blueprintRouter from "./blueprint";
import cultivationsRouter from "./cultivations";
import supportPreferencesRouter from "./supportPreferences";
import knowledgeRouter from "./knowledge";
import calendarRouter from "./calendar";
import tidesRouter from "./tides";
import planningRouter from "./planning";
import tasksRouter from "./tasks";
import habitsRouter from "./habits";
import icalRouter from "./ical";
import pushRouter from "./push";
import googleCalRouter from "./googleCal";
import adviseRouter from "./advise";
import daemonMemoryRouter from "./daemonMemory";
import cycleRouter from "./cycle";
import exportIcalRouter from "./exportIcal";
import currentsRouter from "./currents";
import electionRouter from "./election";

const router: IRouter = Router();

router.use(healthRouter);
router.use(supplementsRouter);
router.use(activitiesRouter);
router.use(logsRouter);
router.use(insightsRouter);
router.use(openaiRouter);
router.use(natalRouter);
router.use(checkInsRouter);
router.use(bodyWeatherRouter);
router.use(astroDebugRouter);
router.use(locationSearchRouter);
router.use(blueprintRouter);
router.use(cultivationsRouter);
router.use(supportPreferencesRouter);
router.use(knowledgeRouter);
router.use(calendarRouter);
router.use(tidesRouter);
router.use(planningRouter);
router.use(tasksRouter);
router.use(habitsRouter);
router.use(icalRouter);
router.use(pushRouter);
router.use(googleCalRouter);
router.use(adviseRouter);
router.use(daemonMemoryRouter);
router.use(cycleRouter);
router.use(exportIcalRouter);
router.use(currentsRouter);
router.use(electionRouter);

export default router;
